### ISSUE TITLE
Missing PersistentVolumeClaim 'shared-fs' after deployment completes 

### ISSUE THREAD

**Issue by aafre** [OasisLMF/OasisAzureDeployment#11]
While trying to deploy the platform and a model (piwind or any other) using the Azure pipeline in this repo, the worker pod appears to be in pending state after the pipelines complete. The event logs show that the pod cannot start due to this missing PVC `shared-fs`.

```
Warning  FailedScheduling 9m24s (x65 over 5h34m)  default-scheduler   0/2 nodes are available: 2 persistentvolumeclaim "shared-fs" not found.
```

I have tried to verify the existence of the `shared-fs` PVC across all namespaces in the cluster, but it seems to be missing.

Could you please help check this issue?

**Comment by benhayes21** [comment]
hi @aafre - is this still an issue? We're cleaning up some old issues and will close if not

**Comment by benhayes21** [comment]
closing for now - can reopen if still an issue
