### ISSUE TITLE
Add check for kubernetesVersion

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisAzureDeployment#5]
The supported kubernetesVersion can change: 
https://github.com/OasisLMF/OasisAzureDeployment/blob/master/azure/bicep/aks.bicep#L7-L8

This returns an error on deployment 
```
Version 1.22.4 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list;
```

The script can check the supported versions in the selected region by running 
`az aks get-versions  --location <region>`

**Comment by benhayes21** [comment]
fixed
